name: deploy

on:
  push:
    branches:    
      - nyamanaka/release_by_ci_test
jobs:
  deploy:
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          server-id: sonatype-nexus-staging
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: check existing
        run: cat $HOME/.m2/settings.xml|grep gpg|wc -l
      - name: Publish to Apache Maven Central
        run: mvn clean deploy -DperformRelease=true
