name: build-and-deploy

on:
  push:
    branches:    
      - nyamanaka/release_by_ci_test
jobs:
  build-and-deploy:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: read 
      statuses: read
      security-events: read
    environment: Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set fake tty
        shell: 'script -q -e -c "bash {0}"'
        run: |
          tty
          export GPG_TTY=$(tty)
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          server-id: sonatype-nexus-staging
          server-username: ${{ secrets.MAVEN_USERNAME }}
          server-password: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: list keys
        run: gpg --list-keys
      - name: version
        run: |
          gpg --version
          java -version
      # - name: check tty
      #   run: |
      #     tty
      #     export GPG_TTY=$(tty)
      - name: gpg test
        shell: 'script -q -e -c "bash {0}"'
        run: mvn -s $HOME/.m2/settings.xml clean install
